version: '3'
services:
    mysql:
        image: mysql:latest
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: selecty
        volumes:
            - ./volumes/mysql:/var/lib/mysql